In [6]:
import cv2
import numpy as np

a = cv2.imread('/home/atharva/vct/commands/table_unclean_test_image.jpeg')
cv2.imshow('heading',a)

cv2.waitKey(0)
cv2.destroyAllWindows()

print(a)

[[[129  39  38]
  [129  40  36]
  [131  40  36]
  ...
  [ 50  20  15]
  [ 50  20  15]
  [ 50  20  15]]

 [[129  40  36]
  [129  40  36]
  [131  40  35]
  ...
  [ 50  20  15]
  [ 50  20  15]
  [ 50  20  15]]

 [[129  41  34]
  [129  41  34]
  [131  42  32]
  ...
  [ 50  20  15]
  [ 50  20  15]
  [ 50  20  15]]

 ...

 [[110 188 211]
  [150 228 251]
  [155 229 253]
  ...
  [168 123 119]
  [166 122 121]
  [166 122 121]]

 [[114 187 217]
  [155 229 255]
  [150 224 250]
  ...
  [167 122 118]
  [167 123 122]
  [166 122 121]]

 [[112 183 216]
  [157 229 255]
  [155 228 255]
  ...
  [167 122 118]
  [167 123 122]
  [166 122 121]]]


In [ ]:
import cv2
import numpy as np

# 4x3 color image, each pixel different color
img = np.array([
    [[255,   0,   0], [0, 255,   0], [0,   0, 255],[255, 255,   0],],   # Blue, Green, Red
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black
], dtype=np.uint8)


#so it is 4*3 matrix 4 column * 3 rows 

# every row should containt same number of column and vice a versa

# these is how 1280*720 pixle image forms

cv2.imshow("3x3 Colors", img)
cv2.waitKqey(0)
cv2.destroyAllWindows()


img = np.array([
    [[0,255,0],[0,0,255],[33,55,22],[22,44,66]],
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black

])


AttributeError: module 'cv2' has no attribute 'waitKqey'

In [6]:
img.shape

(3, 4, 3)

In [ ]:
# how to make bbox on image_Np and save it 


detections =[{'class': 'cash',
  'class_id': 0,
  'confidence': 0.8739702105522156,
  'bbox': [338, 181, 354, 219]},
 {'class': 'cash',
  'class_id': 0,
  'confidence': 0.6799092292785645,
  'bbox': [356, 188, 371, 200]}]


det = detections[0]
x1,y1,x2,y2 = det["bbox"]

for i in detections:
    x1,y1,x2,y2=i["bbox"]
    



cash_box =cv2.rectangle(frame,(x1,y1),(x2,y2),(0,240,0),2)


cv2.imwrite("table_crop_test.jpg",cash_box)


In [2]:
img = np.array([
    [[0,255,0],[0,0,255],[33,55,22],[22,44,66]],
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black

])

cv2.imwrite('test.jpeg',img)

True