In [2]:
import cv2
import numpy as np

a = cv2.imread('/home/atharva/projects/python_basics/images/shape_finder_circles.png')


print(a)
print(a.shape)



[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(1206, 2506, 3)


In [8]:
import cv2
import numpy as np

# 4x3 color image, each pixel different color
img = np.array([
    [[255,   0,   0], [0, 255,   0], [0,   0, 255],[255, 255,   0],],   # Blue, Green, Red
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black
], dtype=np.uint8)


#so it is 4*3 matrix 4 column * 3 rows 

# every row should containt same number of column and vice a versa

# these is how 1280*720 pixle image forms

cv2.imshow("3x3 Colors", img)
cv2.waitKqey(0)
cv2.destroyAllWindows()


img = np.array([
    [[0,255,0],[0,0,255],[33,55,22],[22,44,66]],
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black

])


: 

In [ ]:
img.shape

In [ ]:
# how to make bbox on image_Np and save it 


detections =[{'class': 'cash',
  'class_id': 0,
  'confidence': 0.8739702105522156,
  'bbox': [338, 181, 354, 219]},
 {'class': 'cash',
  'class_id': 0,
  'confidence': 0.6799092292785645,
  'bbox': [356, 188, 371, 200]}]


det = detections[0]
x1,y1,x2,y2 = det["bbox"]

for i in detections:
    x1,y1,x2,y2=i["bbox"]
    



cash_box =cv2.rectangle(frame,(x1,y1),(x2,y2),(0,240,0),2)


cv2.imwrite("table_crop_test.jpg",cash_box)


In [ ]:
img = np.array([
    [[0,255,0],[0,0,255],[33,55,22],[22,44,66]],
    [[255, 255,   0], [0, 255, 255], [255,   0, 255],[255, 255,   0]], # Cyan, Yellow, Magenta
    [[128, 128, 128], [255, 255, 255], [0,   0,   0],[255, 255,   0]]  # Gray, White, Black

])

cv2.imwrite('test.jpeg',img)

In [2]:
print('hi')


hi


In [ ]:
cap = cv2.VideoCapture(0)

while True:
    
    ret,frame = cap.read():
    if not ret:
        break
    
    cv2.imshow(frame)
    cv2.waitKey(0)
    cv2.Distr
        

In [ ]:
#image filtering

# image blurring - smoothening of image

In [ ]:
#gaussian blur

1)smoothening of image soften the image

syntax: cv2.GaussianBlur(src, ksize, sigmaX)

# what is kernal size and sigmaX

ksize: Size of the kernel (should be odd and positive) # moves along the image and applies the blur effect to the neighboring pixels defined by the kernel size window
sigmaX: Standard deviation in the X direction

In [ ]:
#median blur

median blur preserves edges while removing noise. 
It replaces each pixel's value with the median value of the neighboring pixels
defined by the kernel size.

In [ ]:
#sharpening of image - enhance the edges of image and clearify the details of image

cv2.filter2D(src, ddepth, kernel)

In [ ]:
#canny edge detection - detects edges in the image

canny = cv2.Canny(image, threshold1, threshold2)

In [ ]:
#find contours - contours are the curves joining all the continuous points along the boundary of an object in an image
image =cv2.imread('/home/atharva/projects/python_basics/images/shape_finder_circles.png')
contours, hierarchy = cv2.findContours(image, mode, method)