In [14]:
##### PYTORCH #####
IS A FRAMEWORK


1)BUILDING A NEURAL NETWORK
2)TRAINING A NEURAL NETWORK
3)PREDICTING WITH A NEURAL NETWORK

SyntaxError: unmatched ')' (4270624309.py, line 5)

In [ ]:
"""
Input Data
     │
     ▼
Forward Pass
     │
     ▼
Prediction
     │
     ▼
Loss Function
     │
     ▼
Computation Graph Created
     │
     ▼
loss.backward()
     │
     ▼
Gradients Computed
     │
     ▼
Optimizer Updates Parameters
     │
     ▼
Repeat

"""


# PyTorch Workflow - Complete Beginner Notes

## Machine Learning Workflow

Data
↓
Train Model
↓
Learn Pattern
↓
Predict

---

## Step 1: Create Data

Assume:

y = 0.7x + 0.3

Example:

x = 2

y = 0.7(2) + 0.3

y = 1.7

Why create fake data?

Because we already know the correct answer and can check whether the model learns it.

---

## Step 2: Train/Test Split

100 samples

80 -> Training

20 -> Testing

Training data teaches the model.

Testing data checks whether the model learned correctly.

---

## Step 3: Build Model

Model:

y = wx + b

w = weight

b = bias

Initially:

weight and bias are random.

Example:

weight = 0.12

bias = 0.89

Training improves them.

---

## Step 4: Forward Pass

Forward pass means making a prediction.

Example:

x = 5

Prediction:

y = 0.12×5 + 0.89

= 1.49

---

## Step 5: Loss Function

Prediction = 1.49

Actual = 3.8

Loss measures how wrong the prediction is.

Large Loss -> Bad

Small Loss -> Good

---

## Step 6: Optimizer

Optimizer updates weights.

Example:

weight = 0.12

Loss is high.

Optimizer changes:

weight = 0.20

Then:

weight = 0.35

Then:

weight = 0.50

Loss gradually decreases.

---

## Step 7: Training Loop

Predict
↓
Calculate Loss
↓
Update Weights
↓
Repeat

Example:

Epoch 1 -> Loss 10

Epoch 2 -> Loss 7

Epoch 3 -> Loss 4

Epoch 4 -> Loss 2

Epoch 5 -> Loss 0.5

---

## What is an Epoch?

One complete pass through all training data.

100 images

Model sees all 100 images once

= 1 Epoch

---

## Final Goal

Real Formula:

y = 0.7x + 0.3

Model Starts:

y = 0.12x + 0.89

After Training:

y = 0.699x + 0.301

The model discovered the hidden pattern.

---

## CCTV Analytics Example

Image
↓
Neural Network
↓
Features

Human Count
Mobile Count
Crowd Count

↓

Prediction

Human Present?
Crowd Present?
Mobile Detected?

↓

Alert

---

## Quick Revision

Data = Examples

Model = Mathematical Function

Weight = Importance

Bias = Extra Adjustment

Forward Pass = Prediction

Loss = Error

Optimizer = Fixes Weights

Epoch = One Full Learning Cycle

Training = Repeated Improvement


In [ ]:
# Tensors

1) why we require tensors in pytorch
-> tensors is just a container(object) from which networks can learn from it 
-> list and dictionaies cannot changes its size and shape once created. But in pytorch we require tensors which can change its size and shape.
during training of neural networks we require tensors which can change its size and shape. Hence we require tensors in pytorch.

In [ ]:
import torch

print(torch.__version__)

x = torch.tensor([1,2,3])
try:
    y = torch.tensor({"key1": 1, "key2": 2, "key3": 3})
except Exception as e:
    print(f"Error: {e}")
print(x)

type(x)



2.13.0+cu130
Error: Could not infer dtype of dict
tensor([1, 2, 3])


torch.Tensor

In [ ]:
zeros = torch.zeros(4,5)
print(zeros)
random = torch.rand(2,3)
print(random)

#indexing will be same as lists

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0.0975, 0.2310, 0.7460],
        [0.6331, 0.1627, 0.5331]])


In [ ]:
#lets try regression 
import torch

p1 = torch.tensor([1,1])
p2 = torch.tensor([3,2])
p3 = torch.tensor([5,4])
p4 = torch.tensor([6,5])

points=[p1,p2,p3,p4]

n=4
sumation_of_x = p1[0]+p2[0]+p3[0]+p4[0]
sumation_of_y = p1[1]+p2[1]+p3[1]+p4[1]
sumation_of_x_squared=(p1[0])**2+(p2[0])**2+(p3[0])**2+(p4[0])**2
sumation_of_y_squared=(p1[1])**2+(p2[1])**2+(p3[1])**2+(p4[1])**2
summation_of_x_y = p1[0]*p1[1]+p2[0]*p2[1]+p3[0]*p3[1]+p4[0]*p4[1]

slope = (n*summation_of_x_y - sumation_of_x*sumation_of_y)/(n*sumation_of_x_squared -(sumation_of_x)**2)
print(slope)

x_mean = sumation_of_x / n
y_mean = sumation_of_y / n

intercept = y_mean - slope * x_mean

print(intercept)
results={}
MSE=0
for i in points:
    y_pred = slope*i[0]+intercept
    results[i[0]]=y_pred
    MSE+=(y_pred-i[1])**2 
    
print(results)
print(MSE)


tensor(0.8136)
tensor(-0.0508)
{tensor(1): tensor(0.7627), tensor(3): tensor(2.3898), tensor(5): tensor(4.0169), tensor(6): tensor(4.8305)}
tensor(0.2373)


# autograd
pytorch automatically calulate error and adjust weights automatically
parameter is requires_grad = True

# computation graph 

What PyTorch secretly stores

It creates a graph.

          x
          |
       ×3
          |
          y
          |
       +4
          |
          z
          |
      square
          |
        loss

Every operation becomes a node.

PyTorch remembers

multiplication
addition
square

This is called the Computation Graph.


What happens when you call
loss.backward()

PyTorch starts from the end.

loss
↑
z
↑
y
↑
x

It walks backwards through the graph.

This is called Backpropagation.


w.grad is told network how much value should be adjusted and in which direction


In [ ]:
import torch

# Input and target values
x = torch.tensor(2.0)
y_true = torch.tensor(10.0)

# Weight to learn
w = torch.tensor(1.0, requires_grad=True)

# Learning rate
lr = 0.1

# Forward pass
y_pred = w * x
loss = (y_pred - y_true) ** 2

# Backpropagation: calculate gradient
loss.backward()

print("Before update")
print("w:", w.item())
print("loss:", loss.item())
print("gradient:", w.grad.item())

# Update the weight
with torch.no_grad():
    w -= lr * w.grad

# Clear the previous gradient
w.grad.zero_()

print("\nAfter update")
print("w:", w.item())

# Check the new loss
y_pred = w * x
loss = (y_pred - y_true) ** 2
print("new loss:", loss.item())

Before update
w: 1.0
loss: 64.0
gradient: -32.0

After update
w: 4.199999809265137
new loss: 2.5600011348724365


In [ ]:
######training######

import torch

# Training data: y = 2x
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y_true = torch.tensor([2.0, 4.0, 6.0, 8.0])

# Initial weight and learning rate
w = torch.tensor(0.0, requires_grad=True)
lr = 0.1
epochs = 20

for epoch in range(epochs):
    # Step 1: prediction
    y_pred = w * x

    # Step 2: mean squared error loss
    loss = ((y_pred - y_true) ** 2).mean()

    # Step 3: calculate gradient
    loss.backward()

    # Step 4: update weight
    with torch.no_grad():
        w -= lr * w.grad

    # Clear gradients before the next epoch
    w.grad.zero_()

    print(f"Epoch {epoch + 1}: w={w.item():.4f}, loss={loss.item():.4f}")

print("\nFinal weight:", w.item())

# Test prediction
test_x = torch.tensor(5.0)
print(f"Prediction for x={test_x.item()}: {w * test_x:.4f}")

Epoch 1: w=3.0000, loss=30.0000
Epoch 2: w=1.5000, loss=7.5000
Epoch 3: w=2.2500, loss=1.8750
Epoch 4: w=1.8750, loss=0.4688
Epoch 5: w=2.0625, loss=0.1172
Epoch 6: w=1.9688, loss=0.0293
Epoch 7: w=2.0156, loss=0.0073
Epoch 8: w=1.9922, loss=0.0018
Epoch 9: w=2.0039, loss=0.0005
Epoch 10: w=1.9980, loss=0.0001
Epoch 11: w=2.0010, loss=0.0000
Epoch 12: w=1.9995, loss=0.0000
Epoch 13: w=2.0002, loss=0.0000
Epoch 14: w=1.9999, loss=0.0000
Epoch 15: w=2.0001, loss=0.0000
Epoch 16: w=2.0000, loss=0.0000
Epoch 17: w=2.0000, loss=0.0000
Epoch 18: w=2.0000, loss=0.0000
Epoch 19: w=2.0000, loss=0.0000
Epoch 20: w=2.0000, loss=0.0000

Final weight: 1.9999980926513672
Prediction for x=5.0: 10.0000


In neural networks:
Shape: the dimensions of a tensor.
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x.shape)  # torch.Size([2, 2])
This means 2 rows × 2 columns.

Weights (w): learnable values that multiply input features. They determine how important each input is.
y = w * x
In your example, w is one number because there is only one input feature.

Bias (b): an additional learnable value added after multiplication:
y_pred = w * x + b
Bias lets the model fit lines that do not have to pass through zero.

# Rule 1

input should match input feature

# Rule 2 

output will be fixed

# Rule 3

batch size


In [ ]:
#activation function

"""An activation function decides how strongly a neuron “fires” after it calculates:
output = activation(weights * inputs + bias)
Without activation functions, many neural-network layers collapse into one simple linear equation. Activations let networks learn complex patterns.
Common ones:"""

import torch
import torch.nn.functional as F

x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

print(F.relu(x))        # [0, 0, 0, 1, 2]
print(torch.sigmoid(x)) # values between 0 and 1
print(torch.tanh(x))    # values between -1 and 1
ReLU: max(0, x)
# Most common for hidden layers.

# Sigmoid: converts a value to 0–1
# Common for binary classification output, such as spam/not spam.

# Softmax: converts several outputs into probabilities that total 1
# Common for multi-class output, such as cat/dog/bird.

tensor([0., 0., 0., 1., 2.])
tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])


In [ ]:
#optimizer 

# SGD
# Adam




"""An optimizer is the part of training that updates the model’s weights and bias to reduce loss.
prediction → loss → gradients → optimizer updates weights"""


import torch

w = torch.tensor(0.0, requires_grad=True)
optimizer = torch.optim.SGD([w], lr=0.01)

x = torch.tensor(2.0)
y_true = torch.tensor(10.0)

for epoch in range(100):
    y_pred = w * x
    loss = (y_pred - y_true) ** 2

    optimizer.zero_grad()  # remove old gradients
    loss.backward()        # calculate gradients
    optimizer.step()       # update w

print("Weight:", w.item())

Weight: 4.998803615570068


In [ ]:
###saving model

torch.save(model.state_dict(),"linear_model.pth")

'\nInput Data\n     │\n     ▼\nForward Pass\n     │\n     ▼\nPrediction\n     │\n     ▼\nLoss Function\n     │\n     ▼\nComputation Graph Created\n     │\n     ▼\nloss.backward()\n     │\n     ▼\nGradients Computed\n     │\n     ▼\nOptimizer Updates Parameters\n     │\n     ▼\nRepeat\n\n'

In [ ]:
# CNN

# CONVOLUTIONAL MEANS KERNAL SLIDES OVER THE FULL IMAGE

#KERNALS ARE MULTIPLE LAYERS
# 1ST LAYER WILL DETECT LINES , EDGES
# 2ND WILL DETECT CURVERS , CORNERS
# 3RD SHAPES


import torch
import torch.nn as nn

conv = nn.Conv2d(
    in_channels=3,     # RGB image: Red, Green, Blue
    out_channels=16,   # learn 16 different filters/features
    kernel_size=3,     # each filter is 3 × 3
    stride=1,          # move 1 pixel at a time
    padding=1,         # add 1-pixel border
    bias=True
)

image = torch.randn(8, 3, 32, 32)
output = conv(image)

print(output.shape)  # torch.Size([8, 16, 32, 32])

'''
| Parameter | Meaning |
|---|---|
| `in_channels` | Number of channels in the input image. `1` for grayscale, `3` for RGB. |
| `out_channels` | Number of filters the layer learns; also the output-channel count. |
| `kernel_size` | Filter size, e.g. `3` means a `3 × 3` filter. |
| `stride` | How far the filter moves on each step. Larger stride makes output smaller. |
| `padding` | Extra pixels around the image border. |
| `bias` | One learned extra value for each output channel. |
'''

In [ ]:
import torch
import torch.nn as nn

image = torch.randn(1,1,28,28)
print(image.shape)

conv = nn.Conv2d(in_channels=1,out_channels=8,kernel_size=3,stride=1,padding=2)
output = conv(image)


print(f"output shape is {output.shape}")
print(f"input shape is {image.shape}")

torch.Size([1, 1, 28, 28])
output shape is torch.Size([1, 8, 30, 30])
input shape is torch.Size([1, 1, 28, 28])


In [ ]:
### pooling 

# Pooling reduces an image feature map’s height and width while keeping the most useful information.
# It is usually placed after Conv2d + activation:

import torch
import torch.nn as nn

image = torch.randn(1,8,28,28)

pool = nn.MaxPool2d(kernel_size=2)

y = pool(image)

print(image.shape)
print(y.shape)

torch.Size([1, 8, 28, 28])
torch.Size([1, 8, 14, 14])


In [ ]:
### CNN ARCHITECHTURE

'''
Input Image
    ↓
Convolution (Conv2d)
    ↓
Activation (ReLU)
    ↓
Pooling (MaxPool2d)
    ↓
Convolution
    ↓
ReLU
    ↓
Pooling
    ↓
Flatten
    ↓
Fully Connected Layer (Linear)
    ↓
Output Layer
'''

In [15]:
#training of CNN
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Use GPU if available; otherwise use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Download and prepare MNIST dataset
transform = transforms.ToTensor()

train_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)


# CNN model
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),  # 28x28 -> 14x14

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)   # 14x14 -> 7x7
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x


model = CNN().to(device)

# Loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training
epochs = 3

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = loss_fn(outputs, labels)

        # Backward pass and weight update
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    average_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {average_loss:.4f}")


# Testing / accuracy
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        predictions = torch.argmax(outputs, dim=1)

        total += labels.size(0)
        correct += (predictions == labels).sum().item()

accuracy = 100 * correct / total
print(f"Test Accuracy: {accuracy:.2f}%")

Using device: cuda


100.0%
100.0%
100.0%
100.0%


Epoch 1/3, Loss: 0.2256
Epoch 2/3, Loss: 0.0641
Epoch 3/3, Loss: 0.0437
Test Accuracy: 98.72%
