In [ ]:
''' 
PYTORCH VIDEO LINK: https://www.youtube.com/watch?v=V_xro1bcAuA
CNN VIDEO LINK: https://youtu.be/zfiSAzpy9NM?si=G7h96sSl-6dRzQxp
CNN VIDEO LINK: https://youtu.be/pDdP0TFzsoQ?si=dM6H_aolPZkCR3Ux
'''

In [ ]:
STEP 1 - COMPLETE PYTORCH Video

STEP 2 - COMPLETE CNN Video

STEP 3 - Learn Video Analytics (ByteTrack,DeepSORT,Kalman Filter,motion pipelines)

STEP 5 - LEARN ASYNC PROGRAMMING THREDING VS MULTIPROCESSING

In [ ]:

"what is deep learning?


Deep learning is a subset of machine learning that uses neural networks with many layers
(hence "deep") to model and understand complex patterns in data.
It is inspired by the structure and function of the human brain,
particularly the way neurons are connected and communicate with each other.

'WHAT IS PYTORCH?'

PyTorch is an open-source machine learning library developed by Facebook's AI Research lab (FAIR).

In [ ]:
Topic	                    Contents
Introduction to tensors:	Tensors are the basic building block of all of machine learning and deep learning.
Creating tensors:	Tensors can represent almost any kind of data (images, words, tables of numbers).
Getting information from tensors:	If you can put information into a tensor, you'll want to get it out too.
Manipulating tensors:	Machine learning algorithms (like neural networks) involve manipulating tensors in many different ways such as adding, multiplying, combining.
Dealing with tensor shapes:	One of the most common issues in machine learning is dealing with shape mismatches (trying to mix wrong shaped tensors with other tensors).
Indexing on tensors:	If you've indexed on a Python list or NumPy array, it's very similar with tensors, except they can have far more dimensions.
Mixing PyTorch tensors and NumPy:	PyTorch plays with tensors (torch.Tensor), NumPy likes arrays (np.ndarray) sometimes you'll want to mix and match these.
Reproducibility:	Machine learning is very experimental and since it uses a lot of randomness to work, sometimes you'll want that randomness to not be so random.
Running tensors on GPU	GPUs: (Graphics Processing Units) make your code faster, PyTorch makes it easy to run your code on GPUs.

In [4]:
import torch

# 0D Tensor (Scalar)
scalar = torch.tensor(5)
print("Scalar:")
print(scalar)
print("Shape:", scalar.shape)

# 1D Tensor (Vector)
vector = torch.tensor([3,2,2])
print("\nVector:")
print(vector)
print("Shape:", vector.shape)
print("Number of dimensions:", vector.ndim)
# 2D Tensor (Matrix)
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print("\nMatrix:")
print(matrix)
print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)

# 3D Tensor
tensor_3d = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print("\n3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)

Scalar:
tensor(5)
Shape: torch.Size([])

Vector:
tensor([3, 2, 2])
Shape: torch.Size([3])
Number of dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Number of dimensions: 2

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [9]:
import torch 

random_tesor = torch.rand(2,5,3)
print(random_tesor)

tensor([[[0.4361, 0.0137, 0.0577],
         [0.7998, 0.2298, 0.8768],
         [0.5893, 0.8298, 0.8499],
         [0.9003, 0.1418, 0.0507],
         [0.7985, 0.8328, 0.5475]],

        [[0.4466, 0.1217, 0.0936],
         [0.8173, 0.3169, 0.0921],
         [0.6730, 0.8193, 0.2772],
         [0.5706, 0.0254, 0.9688],
         [0.1144, 0.0542, 0.2751]]])


In [7]:

# Create a random tensor of size (224, 224, 3)
import cv2

import numpy as np


random_image_size_tensor = torch.rand(size=(7,5,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
cv2.imwrite("random_image.jpg", random_image_size_tensor.numpy() * 255)

True

In [15]:
# Create a tensor
some_tensor =  torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
    
],device="cuda")

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.int64
Device tensor is stored on: cuda:0


In [31]:
%%time

import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.47 ms, sys: 0 ns, total: 2.47 ms
Wall time: 1.6 ms


tensor(14)

In [32]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 215 μs, sys: 162 μs, total: 377 μs
Wall time: 271 μs


tensor(14)

In [ ]:
y = x @ A.T + b

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.
y is the output (a manipulation of the input in the hopes to discover patterns in it).

SyntaxError: unterminated string literal (detected at line 2) (1345885682.py, line 2)

In [34]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [35]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [36]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [37]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5761, 0.9382, 0.7083, 0.0385],
        [0.4435, 0.5590, 0.5608, 0.9114],
        [0.4711, 0.8452, 0.9706, 0.2929]])

Tensor B:
tensor([[0.0691, 0.1692, 0.9761, 0.5438],
        [0.0941, 0.0554, 0.1449, 0.1506],
        [0.0210, 0.9364, 0.2483, 0.9649]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [38]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

01. PyTorch Workflow Fundamentals

In [ ]:
The essence of machine learning and deep learning is to take some data from the past,
build an algorithm (like a neural network) to discover patterns in it 
and use the discovered patterns to predict the future

In [ ]:
Topic	                Contents
1. Getting data ready:	Data can be almost anything but to get started we're going to create a simple straight line
2. Building a model:	Here we'll create a model to learn patterns in the data, we'll also choose a loss function, optimizer and build a training loop.
3. Fitting the model to data (training):	We've got data and a model, now let's let the model (try to) find patterns in the (training) data.
4. Making predictions and evaluating a model (inference):	Our model's found patterns in the data, let's compare its findings to the actual (testing) data.
5. Saving and loading a model:	You may want to use your model elsewhere, or come back to it later, here we'll cover that.
6. Putting it all together	Let's take all of the above and combine it.

In [ ]:
Split	Purpose	Amount of total data	How often is it used?
Training set	The model learns from this data (like the course materials you study during the semester).	~60-80%	Always
Validation set	The model gets tuned on this data (like the practice exam you take before the final exam).	~10-20%	Often but not always
Testing set	The model gets evaluated on this data to test what it has learned (like the final exam you take at the end of the semester).	~10-20%	Always

In [ ]:
PyTorch module	What does it do?
torch.nn	Contains all of the building blocks for computational graphs (essentially a series of computations executed in a particular way).
torch.nn.Parameter	Stores tensors that can be used with nn.Module. If requires_grad=True gradients (used for updating model parameters via gradient descent) are calculated automatically, this is often referred to as "autograd".
torch.nn.Module	The base class for all neural network modules, all the building blocks for neural networks are subclasses. If you're building a neural network in PyTorch, your models should subclass nn.Module. Requires a forward() method be implemented.
torch.optim	Contains various optimization algorithms (these tell the model parameters stored in nn.Parameter how to best change to improve gradient descent and in turn reduce the loss).
def forward()	All nn.Module subclasses require a forward() method, this defines the computation that will take place on the data passed to the particular nn.Module (e.g. the linear regression formula above).

In [ ]:
Function	What does it do?	Where does it live in PyTorch?	Common values
Loss function	Measures how wrong your model's predictions (e.g. y_preds) are compared to the truth labels (e.g. y_test). Lower the better.	PyTorch has plenty of built-in loss functions in torch.nn.	Mean absolute error (MAE) for regression problems (torch.nn.L1Loss()). Binary cross entropy for binary classification problems (torch.nn.BCELoss()).
Optimizer	Tells your model how to update its internal parameters to best lower the loss.	You can find various optimization function implementations in torch.optim.	Stochastic gradient descent (torch.optim.SGD()). Adam optimizer (torch.optim.Adam()).

In [ ]:
PyTorch training loop
For the training loop, we'll build the following steps:

Number	Step name	What does it do?	Code example
1	Forward pass	The model goes through all of the training data once, performing its forward() function calculations.	model(x_train)
2	Calculate the loss	The model's outputs (predictions) are compared to the ground truth and evaluated to see how wrong they are.	loss = loss_fn(y_pred, y_train)
3	Zero gradients	The optimizers gradients are set to zero (they are accumulated by default) so they can be recalculated for the specific training step.	optimizer.zero_grad()
4	Perform backpropagation on the loss	Computes the gradient of the loss with respect for every model parameter to be updated (each parameter with requires_grad=True). This is known as backpropagation, hence "backwards".	loss.backward()
5	Update the optimizer (gradient descent)	Update the parameters with requires_grad=True with respect to the loss gradients in order to improve them.	optimizer.step()


# PyTorch Workflow - Complete Beginner Notes

## Machine Learning Workflow

Data
↓
Train Model
↓
Learn Pattern
↓
Predict

---

## Step 1: Create Data

Assume:

y = 0.7x + 0.3

Example:

x = 2

y = 0.7(2) + 0.3

y = 1.7

Why create fake data?

Because we already know the correct answer and can check whether the model learns it.

---

## Step 2: Train/Test Split

100 samples

80 -> Training

20 -> Testing

Training data teaches the model.

Testing data checks whether the model learned correctly.

---

## Step 3: Build Model

Model:

y = wx + b

w = weight

b = bias

Initially:

weight and bias are random.

Example:

weight = 0.12

bias = 0.89

Training improves them.

---

## Step 4: Forward Pass

Forward pass means making a prediction.

Example:

x = 5

Prediction:

y = 0.12×5 + 0.89

= 1.49

---

## Step 5: Loss Function

Prediction = 1.49

Actual = 3.8

Loss measures how wrong the prediction is.

Large Loss -> Bad

Small Loss -> Good

---

## Step 6: Optimizer

Optimizer updates weights.

Example:

weight = 0.12

Loss is high.

Optimizer changes:

weight = 0.20

Then:

weight = 0.35

Then:

weight = 0.50

Loss gradually decreases.

---

## Step 7: Training Loop

Predict
↓
Calculate Loss
↓
Update Weights
↓
Repeat

Example:

Epoch 1 -> Loss 10

Epoch 2 -> Loss 7

Epoch 3 -> Loss 4

Epoch 4 -> Loss 2

Epoch 5 -> Loss 0.5

---

## What is an Epoch?

One complete pass through all training data.

100 images

Model sees all 100 images once

= 1 Epoch

---

## Final Goal

Real Formula:

y = 0.7x + 0.3

Model Starts:

y = 0.12x + 0.89

After Training:

y = 0.699x + 0.301

The model discovered the hidden pattern.

---

## CCTV Analytics Example

Image
↓
Neural Network
↓
Features

Human Count
Mobile Count
Crowd Count

↓

Prediction

Human Present?
Crowd Present?
Mobile Detected?

↓

Alert

---

## Quick Revision

Data = Examples

Model = Mathematical Function

Weight = Importance

Bias = Extra Adjustment

Forward Pass = Prediction

Loss = Error

Optimizer = Fixes Weights

Epoch = One Full Learning Cycle

Training = Repeated Improvement


In [1]:
Classification notebook starts with these core ideas:

Concept	Meaning
Regression	Predict number
Classification	Predict category
Binary Classification	Two classes
Multi-Class Classification	Many classes
Neuron	Learns weighted patterns
Weight	Knowledge learned by model
Loss Function	Measures mistake
Optimizer	Updates weights
Sigmoid	Converts output into probability
Hidden Layer	Learns patterns
Activation Function	Adds non-linearity

SyntaxError: invalid syntax (2786798476.py, line 1)